name: mcc provider published
on:
  release:
    types: [published]
    
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Docker Production image
        if: "!github.event.release.prerelease" 
        run: docker build -t chroniccare/clinician:latest -t chroniccare/clinician:${{ github.event.release.tag_name }} .
      - name: Push the Docker Production image to the registry (latest)
        if: "!github.event.release.prerelease"
        run: docker push chroniccare/clinician:latest
      - name: Push the Docker Production image to the registry (${{ github.event.release.tag_name }})
        if: "!github.event.release.prerelease"
        run: docker push chroniccare/clinician:${{ github.event.release.tag_name }}        
      - name: Build the Docker PreRelease image
        if: "github.event.release.prerelease" 
        run: docker build -t  chroniccare/clinician:${{ github.event.release.tag_name }}.pre .
      - name: Push the Docker PreRelease image to the registry
        if: "github.event.release.prerelease"
        run: docker push chroniccare/clinician:${{ github.event.release.tag_name }}.pre       
