name: mcc provider published
on:
  release:
    types: [published]
    
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Docker Production image
        if: "!github.event.release.prerelease" 
        run: docker build -t swmuir/mcc.ecare.clinician:latest .
      - name: Push the Docker Production image to the registry
        if: "!github.event.release.prerelease"
        run: docker push swmuir/mcc.ecare.clinician:latest
      - name: Build the Docker PreRelease image
        if: "github.event.release.prerelease" 
        run: docker build -t swmuir/mcc.ecare.clinician:latest .
      - name: Push the Docker PreRelease image to the registry
        if: "github.event.release.prerelease"
        run: docker push swmuir/mcc.ecare.clinician:latest        
